### ISSUE TITLE
Mvp: Home page

### ISSUE THREAD

**Issue by sonylomo** [sonylomo/data-law-companion#1]
## Tasks
- [x] Hero Banner Image
- [x] News Caroussel
- [x] Kenya Data Protection Act
- [x] Uganda Data Protection Act
- [x] Rwanda Data Protection Act
- [x] FAQ
