### ISSUE TITLE
🚀 Refactor Case Studies Page

### ISSUE THREAD

**Issue by sonylomo** [sonylomo/data-law-companion#27]
## Description
We need to add: https://www.odpc.go.ke/general-guidlines/

## Tasks

- [ ] Filter case studies
- [ ] Add more countries
- [x] Remove images and external links (Do the same for features)
- [x] Dynamically fetch case studies from CMS
